//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace smardMeter.smardWCFServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="adrmap_energymeter", Namespace="http://schemas.datacontract.org/2004/07/smardWeb")]
    public partial class adrmap_energymeter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int addressField;
        
        private string descriptionField;
        
        private string log_columnField;
        
        private int typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int address {
            get {
                return this.addressField;
            }
            set {
                if ((this.addressField.Equals(value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string log_column {
            get {
                return this.log_columnField;
            }
            set {
                if ((object.ReferenceEquals(this.log_columnField, value) != true)) {
                    this.log_columnField = value;
                    this.RaisePropertyChanged("log_column");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="log_energymeter", Namespace="http://schemas.datacontract.org/2004/07/smardWeb")]
    public partial class log_energymeter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> cosphi_l1Field;
        
        private System.Nullable<int> cosphi_l2Field;
        
        private System.Nullable<int> cosphi_l3Field;
        
        private int deviceField;
        
        private int logtimeField;
        
        private System.Nullable<int> p_in_all_actField;
        
        private System.Nullable<long> p_in_all_sumField;
        
        private System.Nullable<int> p_in_l1_actField;
        
        private System.Nullable<long> p_in_l1_sumField;
        
        private System.Nullable<int> p_in_l2_actField;
        
        private System.Nullable<long> p_in_l2_sumField;
        
        private System.Nullable<int> p_in_l3_actField;
        
        private System.Nullable<long> p_in_l3_sumField;
        
        private System.Nullable<int> p_out_all_act1Field;
        
        private System.Nullable<long> p_out_all_sumField;
        
        private System.Nullable<int> p_out_l1_act1Field;
        
        private System.Nullable<long> p_out_l1_sumField;
        
        private System.Nullable<int> p_out_l2_act1Field;
        
        private System.Nullable<long> p_out_l2_sumField;
        
        private System.Nullable<int> p_out_l3_act1Field;
        
        private System.Nullable<long> p_out_l3_sumField;
        
        private System.Nullable<int> q_in_all_act1Field;
        
        private System.Nullable<long> q_in_all_sumField;
        
        private System.Nullable<int> q_in_l1_act1Field;
        
        private System.Nullable<long> q_in_l1_sumField;
        
        private System.Nullable<int> q_in_l2_act1Field;
        
        private System.Nullable<long> q_in_l2_sumField;
        
        private System.Nullable<int> q_in_l3_act1Field;
        
        private System.Nullable<long> q_in_l3_sumField;
        
        private System.Nullable<int> q_out_all_act1Field;
        
        private System.Nullable<long> q_out_all_sumField;
        
        private System.Nullable<int> q_out_l1_act1Field;
        
        private System.Nullable<long> q_out_l1_sumField;
        
        private System.Nullable<int> q_out_l2_act1Field;
        
        private System.Nullable<long> q_out_l2_sumField;
        
        private System.Nullable<int> q_out_l3_act1Field;
        
        private System.Nullable<long> q_out_l3_sumField;
        
        private System.Nullable<int> s_in_all_act1Field;
        
        private System.Nullable<long> s_in_all_sumField;
        
        private System.Nullable<int> s_in_l1_act1Field;
        
        private System.Nullable<long> s_in_l1_sumField;
        
        private System.Nullable<int> s_in_l2_act1Field;
        
        private System.Nullable<long> s_in_l2_sumField;
        
        private System.Nullable<int> s_in_l3_act1Field;
        
        private System.Nullable<long> s_in_l3_sumField;
        
        private System.Nullable<int> s_out_all_act1Field;
        
        private System.Nullable<int> s_out_l1_act1Field;
        
        private System.Nullable<int> s_out_l2_act1Field;
        
        private System.Nullable<int> s_out_l3_act1Field;
        
        private smardMeter.smardWCFServiceReference.smadevice smadeviceField;
        
        private System.Nullable<int> thd_l1Field;
        
        private System.Nullable<int> thd_l2Field;
        
        private System.Nullable<int> thd_l3Field;
        
        private System.Nullable<int> v_l1Field;
        
        private System.Nullable<int> v_l2Field;
        
        private System.Nullable<int> v_l3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cosphi_l1 {
            get {
                return this.cosphi_l1Field;
            }
            set {
                if ((this.cosphi_l1Field.Equals(value) != true)) {
                    this.cosphi_l1Field = value;
                    this.RaisePropertyChanged("cosphi_l1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cosphi_l2 {
            get {
                return this.cosphi_l2Field;
            }
            set {
                if ((this.cosphi_l2Field.Equals(value) != true)) {
                    this.cosphi_l2Field = value;
                    this.RaisePropertyChanged("cosphi_l2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cosphi_l3 {
            get {
                return this.cosphi_l3Field;
            }
            set {
                if ((this.cosphi_l3Field.Equals(value) != true)) {
                    this.cosphi_l3Field = value;
                    this.RaisePropertyChanged("cosphi_l3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int device {
            get {
                return this.deviceField;
            }
            set {
                if ((this.deviceField.Equals(value) != true)) {
                    this.deviceField = value;
                    this.RaisePropertyChanged("device");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logtime {
            get {
                return this.logtimeField;
            }
            set {
                if ((this.logtimeField.Equals(value) != true)) {
                    this.logtimeField = value;
                    this.RaisePropertyChanged("logtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_in_all_act {
            get {
                return this.p_in_all_actField;
            }
            set {
                if ((this.p_in_all_actField.Equals(value) != true)) {
                    this.p_in_all_actField = value;
                    this.RaisePropertyChanged("p_in_all_act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_in_all_sum {
            get {
                return this.p_in_all_sumField;
            }
            set {
                if ((this.p_in_all_sumField.Equals(value) != true)) {
                    this.p_in_all_sumField = value;
                    this.RaisePropertyChanged("p_in_all_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_in_l1_act {
            get {
                return this.p_in_l1_actField;
            }
            set {
                if ((this.p_in_l1_actField.Equals(value) != true)) {
                    this.p_in_l1_actField = value;
                    this.RaisePropertyChanged("p_in_l1_act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_in_l1_sum {
            get {
                return this.p_in_l1_sumField;
            }
            set {
                if ((this.p_in_l1_sumField.Equals(value) != true)) {
                    this.p_in_l1_sumField = value;
                    this.RaisePropertyChanged("p_in_l1_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_in_l2_act {
            get {
                return this.p_in_l2_actField;
            }
            set {
                if ((this.p_in_l2_actField.Equals(value) != true)) {
                    this.p_in_l2_actField = value;
                    this.RaisePropertyChanged("p_in_l2_act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_in_l2_sum {
            get {
                return this.p_in_l2_sumField;
            }
            set {
                if ((this.p_in_l2_sumField.Equals(value) != true)) {
                    this.p_in_l2_sumField = value;
                    this.RaisePropertyChanged("p_in_l2_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_in_l3_act {
            get {
                return this.p_in_l3_actField;
            }
            set {
                if ((this.p_in_l3_actField.Equals(value) != true)) {
                    this.p_in_l3_actField = value;
                    this.RaisePropertyChanged("p_in_l3_act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_in_l3_sum {
            get {
                return this.p_in_l3_sumField;
            }
            set {
                if ((this.p_in_l3_sumField.Equals(value) != true)) {
                    this.p_in_l3_sumField = value;
                    this.RaisePropertyChanged("p_in_l3_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_out_all_act1 {
            get {
                return this.p_out_all_act1Field;
            }
            set {
                if ((this.p_out_all_act1Field.Equals(value) != true)) {
                    this.p_out_all_act1Field = value;
                    this.RaisePropertyChanged("p_out_all_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_out_all_sum {
            get {
                return this.p_out_all_sumField;
            }
            set {
                if ((this.p_out_all_sumField.Equals(value) != true)) {
                    this.p_out_all_sumField = value;
                    this.RaisePropertyChanged("p_out_all_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_out_l1_act1 {
            get {
                return this.p_out_l1_act1Field;
            }
            set {
                if ((this.p_out_l1_act1Field.Equals(value) != true)) {
                    this.p_out_l1_act1Field = value;
                    this.RaisePropertyChanged("p_out_l1_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_out_l1_sum {
            get {
                return this.p_out_l1_sumField;
            }
            set {
                if ((this.p_out_l1_sumField.Equals(value) != true)) {
                    this.p_out_l1_sumField = value;
                    this.RaisePropertyChanged("p_out_l1_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_out_l2_act1 {
            get {
                return this.p_out_l2_act1Field;
            }
            set {
                if ((this.p_out_l2_act1Field.Equals(value) != true)) {
                    this.p_out_l2_act1Field = value;
                    this.RaisePropertyChanged("p_out_l2_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_out_l2_sum {
            get {
                return this.p_out_l2_sumField;
            }
            set {
                if ((this.p_out_l2_sumField.Equals(value) != true)) {
                    this.p_out_l2_sumField = value;
                    this.RaisePropertyChanged("p_out_l2_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_out_l3_act1 {
            get {
                return this.p_out_l3_act1Field;
            }
            set {
                if ((this.p_out_l3_act1Field.Equals(value) != true)) {
                    this.p_out_l3_act1Field = value;
                    this.RaisePropertyChanged("p_out_l3_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> p_out_l3_sum {
            get {
                return this.p_out_l3_sumField;
            }
            set {
                if ((this.p_out_l3_sumField.Equals(value) != true)) {
                    this.p_out_l3_sumField = value;
                    this.RaisePropertyChanged("p_out_l3_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_in_all_act1 {
            get {
                return this.q_in_all_act1Field;
            }
            set {
                if ((this.q_in_all_act1Field.Equals(value) != true)) {
                    this.q_in_all_act1Field = value;
                    this.RaisePropertyChanged("q_in_all_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_in_all_sum {
            get {
                return this.q_in_all_sumField;
            }
            set {
                if ((this.q_in_all_sumField.Equals(value) != true)) {
                    this.q_in_all_sumField = value;
                    this.RaisePropertyChanged("q_in_all_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_in_l1_act1 {
            get {
                return this.q_in_l1_act1Field;
            }
            set {
                if ((this.q_in_l1_act1Field.Equals(value) != true)) {
                    this.q_in_l1_act1Field = value;
                    this.RaisePropertyChanged("q_in_l1_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_in_l1_sum {
            get {
                return this.q_in_l1_sumField;
            }
            set {
                if ((this.q_in_l1_sumField.Equals(value) != true)) {
                    this.q_in_l1_sumField = value;
                    this.RaisePropertyChanged("q_in_l1_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_in_l2_act1 {
            get {
                return this.q_in_l2_act1Field;
            }
            set {
                if ((this.q_in_l2_act1Field.Equals(value) != true)) {
                    this.q_in_l2_act1Field = value;
                    this.RaisePropertyChanged("q_in_l2_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_in_l2_sum {
            get {
                return this.q_in_l2_sumField;
            }
            set {
                if ((this.q_in_l2_sumField.Equals(value) != true)) {
                    this.q_in_l2_sumField = value;
                    this.RaisePropertyChanged("q_in_l2_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_in_l3_act1 {
            get {
                return this.q_in_l3_act1Field;
            }
            set {
                if ((this.q_in_l3_act1Field.Equals(value) != true)) {
                    this.q_in_l3_act1Field = value;
                    this.RaisePropertyChanged("q_in_l3_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_in_l3_sum {
            get {
                return this.q_in_l3_sumField;
            }
            set {
                if ((this.q_in_l3_sumField.Equals(value) != true)) {
                    this.q_in_l3_sumField = value;
                    this.RaisePropertyChanged("q_in_l3_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_out_all_act1 {
            get {
                return this.q_out_all_act1Field;
            }
            set {
                if ((this.q_out_all_act1Field.Equals(value) != true)) {
                    this.q_out_all_act1Field = value;
                    this.RaisePropertyChanged("q_out_all_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_out_all_sum {
            get {
                return this.q_out_all_sumField;
            }
            set {
                if ((this.q_out_all_sumField.Equals(value) != true)) {
                    this.q_out_all_sumField = value;
                    this.RaisePropertyChanged("q_out_all_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_out_l1_act1 {
            get {
                return this.q_out_l1_act1Field;
            }
            set {
                if ((this.q_out_l1_act1Field.Equals(value) != true)) {
                    this.q_out_l1_act1Field = value;
                    this.RaisePropertyChanged("q_out_l1_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_out_l1_sum {
            get {
                return this.q_out_l1_sumField;
            }
            set {
                if ((this.q_out_l1_sumField.Equals(value) != true)) {
                    this.q_out_l1_sumField = value;
                    this.RaisePropertyChanged("q_out_l1_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_out_l2_act1 {
            get {
                return this.q_out_l2_act1Field;
            }
            set {
                if ((this.q_out_l2_act1Field.Equals(value) != true)) {
                    this.q_out_l2_act1Field = value;
                    this.RaisePropertyChanged("q_out_l2_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_out_l2_sum {
            get {
                return this.q_out_l2_sumField;
            }
            set {
                if ((this.q_out_l2_sumField.Equals(value) != true)) {
                    this.q_out_l2_sumField = value;
                    this.RaisePropertyChanged("q_out_l2_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> q_out_l3_act1 {
            get {
                return this.q_out_l3_act1Field;
            }
            set {
                if ((this.q_out_l3_act1Field.Equals(value) != true)) {
                    this.q_out_l3_act1Field = value;
                    this.RaisePropertyChanged("q_out_l3_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> q_out_l3_sum {
            get {
                return this.q_out_l3_sumField;
            }
            set {
                if ((this.q_out_l3_sumField.Equals(value) != true)) {
                    this.q_out_l3_sumField = value;
                    this.RaisePropertyChanged("q_out_l3_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_in_all_act1 {
            get {
                return this.s_in_all_act1Field;
            }
            set {
                if ((this.s_in_all_act1Field.Equals(value) != true)) {
                    this.s_in_all_act1Field = value;
                    this.RaisePropertyChanged("s_in_all_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> s_in_all_sum {
            get {
                return this.s_in_all_sumField;
            }
            set {
                if ((this.s_in_all_sumField.Equals(value) != true)) {
                    this.s_in_all_sumField = value;
                    this.RaisePropertyChanged("s_in_all_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_in_l1_act1 {
            get {
                return this.s_in_l1_act1Field;
            }
            set {
                if ((this.s_in_l1_act1Field.Equals(value) != true)) {
                    this.s_in_l1_act1Field = value;
                    this.RaisePropertyChanged("s_in_l1_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> s_in_l1_sum {
            get {
                return this.s_in_l1_sumField;
            }
            set {
                if ((this.s_in_l1_sumField.Equals(value) != true)) {
                    this.s_in_l1_sumField = value;
                    this.RaisePropertyChanged("s_in_l1_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_in_l2_act1 {
            get {
                return this.s_in_l2_act1Field;
            }
            set {
                if ((this.s_in_l2_act1Field.Equals(value) != true)) {
                    this.s_in_l2_act1Field = value;
                    this.RaisePropertyChanged("s_in_l2_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> s_in_l2_sum {
            get {
                return this.s_in_l2_sumField;
            }
            set {
                if ((this.s_in_l2_sumField.Equals(value) != true)) {
                    this.s_in_l2_sumField = value;
                    this.RaisePropertyChanged("s_in_l2_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_in_l3_act1 {
            get {
                return this.s_in_l3_act1Field;
            }
            set {
                if ((this.s_in_l3_act1Field.Equals(value) != true)) {
                    this.s_in_l3_act1Field = value;
                    this.RaisePropertyChanged("s_in_l3_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> s_in_l3_sum {
            get {
                return this.s_in_l3_sumField;
            }
            set {
                if ((this.s_in_l3_sumField.Equals(value) != true)) {
                    this.s_in_l3_sumField = value;
                    this.RaisePropertyChanged("s_in_l3_sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_out_all_act1 {
            get {
                return this.s_out_all_act1Field;
            }
            set {
                if ((this.s_out_all_act1Field.Equals(value) != true)) {
                    this.s_out_all_act1Field = value;
                    this.RaisePropertyChanged("s_out_all_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_out_l1_act1 {
            get {
                return this.s_out_l1_act1Field;
            }
            set {
                if ((this.s_out_l1_act1Field.Equals(value) != true)) {
                    this.s_out_l1_act1Field = value;
                    this.RaisePropertyChanged("s_out_l1_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_out_l2_act1 {
            get {
                return this.s_out_l2_act1Field;
            }
            set {
                if ((this.s_out_l2_act1Field.Equals(value) != true)) {
                    this.s_out_l2_act1Field = value;
                    this.RaisePropertyChanged("s_out_l2_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> s_out_l3_act1 {
            get {
                return this.s_out_l3_act1Field;
            }
            set {
                if ((this.s_out_l3_act1Field.Equals(value) != true)) {
                    this.s_out_l3_act1Field = value;
                    this.RaisePropertyChanged("s_out_l3_act1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public smardMeter.smardWCFServiceReference.smadevice smadevice {
            get {
                return this.smadeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.smadeviceField, value) != true)) {
                    this.smadeviceField = value;
                    this.RaisePropertyChanged("smadevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> thd_l1 {
            get {
                return this.thd_l1Field;
            }
            set {
                if ((this.thd_l1Field.Equals(value) != true)) {
                    this.thd_l1Field = value;
                    this.RaisePropertyChanged("thd_l1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> thd_l2 {
            get {
                return this.thd_l2Field;
            }
            set {
                if ((this.thd_l2Field.Equals(value) != true)) {
                    this.thd_l2Field = value;
                    this.RaisePropertyChanged("thd_l2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> thd_l3 {
            get {
                return this.thd_l3Field;
            }
            set {
                if ((this.thd_l3Field.Equals(value) != true)) {
                    this.thd_l3Field = value;
                    this.RaisePropertyChanged("thd_l3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> v_l1 {
            get {
                return this.v_l1Field;
            }
            set {
                if ((this.v_l1Field.Equals(value) != true)) {
                    this.v_l1Field = value;
                    this.RaisePropertyChanged("v_l1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> v_l2 {
            get {
                return this.v_l2Field;
            }
            set {
                if ((this.v_l2Field.Equals(value) != true)) {
                    this.v_l2Field = value;
                    this.RaisePropertyChanged("v_l2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> v_l3 {
            get {
                return this.v_l3Field;
            }
            set {
                if ((this.v_l3Field.Equals(value) != true)) {
                    this.v_l3Field = value;
                    this.RaisePropertyChanged("v_l3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="smadevice", Namespace="http://schemas.datacontract.org/2004/07/smardWeb")]
    public partial class smadevice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deviceIDField;
        
        private int devicetypeField;
        
        private string firmwareField;
        
        private string hostnameField;
        
        private string ipaddressField;
        
        private System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.log_energymeter> log_energymeterField;
        
        private System.Nullable<decimal> serialnumberField;
        
        private smardMeter.smardWCFServiceReference.smadevicetype smadevicetypeField;
        
        private string targetaddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deviceID {
            get {
                return this.deviceIDField;
            }
            set {
                if ((this.deviceIDField.Equals(value) != true)) {
                    this.deviceIDField = value;
                    this.RaisePropertyChanged("deviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int devicetype {
            get {
                return this.devicetypeField;
            }
            set {
                if ((this.devicetypeField.Equals(value) != true)) {
                    this.devicetypeField = value;
                    this.RaisePropertyChanged("devicetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firmware {
            get {
                return this.firmwareField;
            }
            set {
                if ((object.ReferenceEquals(this.firmwareField, value) != true)) {
                    this.firmwareField = value;
                    this.RaisePropertyChanged("firmware");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                if ((object.ReferenceEquals(this.hostnameField, value) != true)) {
                    this.hostnameField = value;
                    this.RaisePropertyChanged("hostname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ipaddress {
            get {
                return this.ipaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ipaddressField, value) != true)) {
                    this.ipaddressField = value;
                    this.RaisePropertyChanged("ipaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.log_energymeter> log_energymeter {
            get {
                return this.log_energymeterField;
            }
            set {
                if ((object.ReferenceEquals(this.log_energymeterField, value) != true)) {
                    this.log_energymeterField = value;
                    this.RaisePropertyChanged("log_energymeter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> serialnumber {
            get {
                return this.serialnumberField;
            }
            set {
                if ((this.serialnumberField.Equals(value) != true)) {
                    this.serialnumberField = value;
                    this.RaisePropertyChanged("serialnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public smardMeter.smardWCFServiceReference.smadevicetype smadevicetype {
            get {
                return this.smadevicetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.smadevicetypeField, value) != true)) {
                    this.smadevicetypeField = value;
                    this.RaisePropertyChanged("smadevicetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetaddress {
            get {
                return this.targetaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.targetaddressField, value) != true)) {
                    this.targetaddressField = value;
                    this.RaisePropertyChanged("targetaddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="smadevicetype", Namespace="http://schemas.datacontract.org/2004/07/smardWeb")]
    public partial class smadevicetype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string devicetypeClassField;
        
        private int devicetypeIDField;
        
        private string devicetypeNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.smadevice> smadevicesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string devicetypeClass {
            get {
                return this.devicetypeClassField;
            }
            set {
                if ((object.ReferenceEquals(this.devicetypeClassField, value) != true)) {
                    this.devicetypeClassField = value;
                    this.RaisePropertyChanged("devicetypeClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int devicetypeID {
            get {
                return this.devicetypeIDField;
            }
            set {
                if ((this.devicetypeIDField.Equals(value) != true)) {
                    this.devicetypeIDField = value;
                    this.RaisePropertyChanged("devicetypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string devicetypeName {
            get {
                return this.devicetypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.devicetypeNameField, value) != true)) {
                    this.devicetypeNameField = value;
                    this.RaisePropertyChanged("devicetypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.smadevice> smadevices {
            get {
                return this.smadevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.smadevicesField, value) != true)) {
                    this.smadevicesField = value;
                    this.RaisePropertyChanged("smadevices");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="smardWCFServiceReference.IsmardWCFService")]
    public interface IsmardWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsmardWCFService/GetAddressMap_EnergyMeter", ReplyAction="http://tempuri.org/IsmardWCFService/GetAddressMap_EnergyMeterResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.adrmap_energymeter>> GetAddressMap_EnergyMeterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsmardWCFService/GetLogRaw_EnergyMeter", ReplyAction="http://tempuri.org/IsmardWCFService/GetLogRaw_EnergyMeterResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.log_energymeter>> GetLogRaw_EnergyMeterAsync(int deviceID, int iTypeID, int bStartTime, int bEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsmardWCFService/AddDevice", ReplyAction="http://tempuri.org/IsmardWCFService/AddDeviceResponse")]
        System.Threading.Tasks.Task<int> AddDeviceAsync(int iTypeID, System.Nullable<decimal> dSerialNumber, string sHostname, string sIPAddress, string sTargetAddress, string sFirmware);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsmardWCFService/GetDevice", ReplyAction="http://tempuri.org/IsmardWCFService/GetDeviceResponse")]
        System.Threading.Tasks.Task<int> GetDeviceAsync(System.Nullable<decimal> dSerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsmardWCFService/AddLogEntry_EnergyMeter", ReplyAction="http://tempuri.org/IsmardWCFService/AddLogEntry_EnergyMeterResponse")]
        System.Threading.Tasks.Task<int> AddLogEntry_EnergyMeterAsync(smardMeter.smardWCFServiceReference.log_energymeter logdata);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsmardWCFServiceChannel : smardMeter.smardWCFServiceReference.IsmardWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsmardWCFServiceClient : System.ServiceModel.ClientBase<smardMeter.smardWCFServiceReference.IsmardWCFService>, smardMeter.smardWCFServiceReference.IsmardWCFService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IsmardWCFServiceClient() : 
                base(IsmardWCFServiceClient.GetDefaultBinding(), IsmardWCFServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IsmardWCFService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmardWCFServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IsmardWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), IsmardWCFServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmardWCFServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IsmardWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmardWCFServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IsmardWCFServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmardWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.adrmap_energymeter>> GetAddressMap_EnergyMeterAsync() {
            return base.Channel.GetAddressMap_EnergyMeterAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<smardMeter.smardWCFServiceReference.log_energymeter>> GetLogRaw_EnergyMeterAsync(int deviceID, int iTypeID, int bStartTime, int bEndTime) {
            return base.Channel.GetLogRaw_EnergyMeterAsync(deviceID, iTypeID, bStartTime, bEndTime);
        }
        
        public System.Threading.Tasks.Task<int> AddDeviceAsync(int iTypeID, System.Nullable<decimal> dSerialNumber, string sHostname, string sIPAddress, string sTargetAddress, string sFirmware) {
            return base.Channel.AddDeviceAsync(iTypeID, dSerialNumber, sHostname, sIPAddress, sTargetAddress, sFirmware);
        }
        
        public System.Threading.Tasks.Task<int> GetDeviceAsync(System.Nullable<decimal> dSerialNumber) {
            return base.Channel.GetDeviceAsync(dSerialNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddLogEntry_EnergyMeterAsync(smardMeter.smardWCFServiceReference.log_energymeter logdata) {
            return base.Channel.AddLogEntry_EnergyMeterAsync(logdata);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IsmardWCFService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IsmardWCFService)) {
                return new System.ServiceModel.EndpointAddress("http://smard.azurewebsites.net/smardWCFService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return IsmardWCFServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IsmardWCFService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return IsmardWCFServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IsmardWCFService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IsmardWCFService,
        }
    }
}
